services:
  maria-db:
    image: docker.io/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MYSQL_DATABASE=db
    ports:
      - 3307:3306
    volumes:
      - type: bind
        source: ./relational-init-scripts
        target: /docker-entrypoint-initdb.d
        
  dbeaver:
    image: docker.io/dbeaver/cloudbeaver
    ports:
      - 8978:8978
    volumes:
      - type: bind
        source: ./dbeaver-data
        target: /opt/cloudbeaver/workspace

  mongo:
    image: docker.io/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./mongo-init-scripts
        target: /docker-entrypoint-initdb.d

  mongo-express:
    image: docker.io/mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    restart: unless-stopped